import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Container, Grid, Card, CardMedia, Typography } from "@mui/material";
import Link from "next/link";
import Layout from "@/components/TopBarComponents/Layout";
import { cardStyle, cardMediaStyle } from "@/utils/Styles";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
       <Layout>
        <Container sx={{
            minHeight: '100vh', // Usa minHeight ao invés de height para melhor responsividade
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            padding: '16px', // Adiciona algum espaçamento em volta do conteúdo
            '@media (max-width:600px)': {
              minHeight: 'calc(100vh - 56px)', // Altura ajustada para considerar a AppBar em dispositivos móveis
              textAlign:"center"
            }
          }}>
            <Grid container spacing={4} sx={{
              maxWidth: 'md', // Define a largura máxima do grid para que não fique muito espaçado
              justifyContent: 'space-around', // Centraliza horizontalmente os Grid items
            }}>
                <Grid item xs={12} sm={6} md={3}>
                <Link href="/StudentRegistration" style={{ textDecoration: 'none', color: 'inherit' }}>
                  {" "}
                  {/* Adiciona o link para o Card */}
                  <Card sx={cardStyle}>
                    <CardMedia
                      sx={cardMediaStyle}
                      component="img"
                      height="fit-content"
                      width="fit-content"
                      image="https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fresume.png?alt=media&token=6edbaf5e-7e2b-40a0-a3e2-9811e3631a75"
                      alt=""
                    />
                    <Typography color="#FFFF" mt={3} variant="h5">
                      Cadastro de Atletas
                    </Typography>
                    <Typography color="#FFFF" mt={27} variant="h5"></Typography>
                  </Card>
                </Link>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Link href="/StudentUpdatePersonalInformation" style={{ textDecoration: 'none', color: 'inherit' }}>
                  {" "}
                  {/* Adiciona o link para o Card */}
                  <Card sx={cardStyle}>
                    <CardMedia
                      sx={cardMediaStyle}
                      component="img"
                      height="fit-content"
                      width="fit-content"
                      image="https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fupdate.png?alt=media&token=bc1e2318-041e-4154-8f27-8d0a9faa80ae"
                      alt=""
                    />
                    <Typography color="#FFFF" mt={3} variant="h5">
                      Atualização de dados
                    </Typography>
                    <Typography color="#FFFF" mt={27} variant="h5"></Typography>
                  </Card>
                </Link>
              </Grid>
              <Grid item xs={12} sm={6} md={3}>
                <Link href="/StudentPresenceTable" style={{ textDecoration: 'none', color: 'inherit' }}>
                  {" "}
                  {/* Adiciona o link para o Card */}
                  <Card sx={cardStyle}>
                    <CardMedia
                      sx={cardMediaStyle}
                      component="img"
                      height="fit-content"
                      width="fit-content"
                      image="https://firebasestorage.googleapis.com/v0/b/chat-dos-otarios.appspot.com/o/ceab%2Fchecklist.png?alt=media&token=95d85403-ac4e-49a2-a546-cd7615c6ff50"
                      alt=""
                    />
                    <Typography color="#FFFF" mt={3} variant="h5">
                      Registro de frequencia
                    </Typography>
                    <Typography color="#FFFF" mt={27} variant="h5"></Typography>
                  </Card>
                </Link>
              </Grid>
            </Grid>
          </Container>
          </Layout>
      </main>
    </>
  );
}
